@startuml
left to right direction
skinparam packageStyle rectangle
skinparam shadowing false

actor "Résident" as Resident
actor "Syndic" as Syndic
actor "Administrateur" as Admin

rectangle "Système ImmoSyndic - Sprint 1 (MVP)" {

  ' Authentification commune
  usecase "S'authentifier" as Auth
  usecase "Gérer son profil" as Profile

  Resident -- Auth
  Syndic -- Auth
  Admin -- Auth
  
  Resident -- Profile
  Syndic -- Profile
  Admin -- Profile

  package "Espace Résident" {
    Resident -- (Créer un compte)
    Resident -- (Consulter les charges et paiements)
    Resident -- (Signaler un problème ou une intervention)
    Resident -- (Recevoir des notifications de paiement)
  }

  package "Espace Syndic" {
    Syndic -- (Gérer les informations des immeubles)
    Syndic -- (Suivre les paiements des résidents)
    Syndic -- (Générer des reçus de paiement)
    Syndic -- (suivre les interventions)
    Syndic -- (Consulter l'historique des actions)
  }

  package "Espace Administrateur" {
    Admin -- (Gérer les comptes utilisateurs)
    Admin -- (Superviser les immeubles et paiements)
    Admin -- (Valider les données du système)
  }

}
@enduml