@startuml ImmoSyndic_Global_Syndic
left to right direction
skinparam packageStyle rectangle
skinparam shadowing false

actor "Syndic" as Syndic

rectangle "Système ImmoSyndic - Global (Vision Syndic)" {

  package "Authentification" {
    usecase "S'authentifier" as Auth
  }

  package "Portail Web (Gestion)" {
    package "Espace Syndic (Web)" {
      usecase "Créer compte" as Register
      usecase "Gérer les Résidents" as ManageResidents
      usecase "Gérer immeubles" as ManageBuildings
      usecase "Suivre paiements" as TrackPayments
      usecase "Générer reçus" as GenReceipts
      usecase "Suivre interventions" as TrackInterventions
      usecase "Gérer planning" as ManagePlanning
      usecase "Analyser statistiques" as ViewStats
      usecase "Envoyer annonces" as SendNews
      usecase "Gérer archivage" as ArchiveDocs

      Register ..> Auth : <<include>>
      ManageResidents ..> Auth : <<include>>
      ManageBuildings ..> Auth : <<include>>
      TrackPayments ..> Auth : <<include>>
      GenReceipts ..> Auth : <<include>>
      TrackInterventions ..> Auth : <<include>>
      ManagePlanning ..> Auth : <<include>>
      ViewStats ..> Auth : <<include>>
      SendNews ..> Auth : <<include>>
      ArchiveDocs ..> Auth : <<include>>
    }
  }
}

' Web Connections
Syndic -- Register
Syndic -- ManageResidents
Syndic -- ManageBuildings
Syndic -- TrackPayments
Syndic -- GenReceipts
Syndic -- TrackInterventions
Syndic -- ManagePlanning
Syndic -- ViewStats
Syndic -- SendNews
Syndic -- ArchiveDocs

@enduml
