@startuml ImmoSyndic_Global_Mobile
left to right direction
skinparam packageStyle rectangle
skinparam shadowing false

actor "Résident" as Resident
actor "Web" as Web <<System>>

rectangle "Application Mobile ImmoSyndic" {

  package "Session" {
    usecase "S'authentifier" as Auth
  }

  package "Services API (Consultation)" {
    usecase "Fournir API" as ProvideAPI
    usecase "API Consulter mes charges" as APIMobileViewCharges
    usecase "API Voir mes notifications" as APIMobileViewNotifs
    usecase "API Consulter archives" as APIMobileViewArchives

    ProvideAPI ..> APIMobileViewCharges : <<include>>
    ProvideAPI ..> APIMobileViewNotifs : <<include>>
    ProvideAPI ..> APIMobileViewArchives : <<include>>

    APIMobileViewCharges ..> Auth : <<include>>
    APIMobileViewNotifs ..> Auth : <<include>>
    APIMobileViewArchives ..> Auth : <<include>>
  }
}

' Users Connections
Resident -- APIMobileViewCharges
Resident -- APIMobileViewNotifs
Resident -- APIMobileViewArchives

' Backend Connections (Data Source)
Web -- ProvideAPI

@enduml
