@startuml
left to right direction
skinparam packageStyle rectangle
skinparam shadowing false

' Actors
actor "Visiteur (Public)" as Visitor
actor "Client " as Client
actor "Co-coach (Staff)" as Staff
actor "Coach (Admin)" as Admin

' Hierarchy
Staff <|-- Admin

rectangle "Coach Management System" {
  
  package "Plateforme Publique (Vitrine)" {
    usecase "Consulter les tarifs & services" as ViewPublic
    usecase "S'inscrire (Nouveau Coach)" as Signup
  }

  package "Authentification & Sécurité" {
    usecase "S'authentifier (Login)" as Login
  }

  package "Espace Client (Web/Desktop)" {
    usecase "Mettre à jour poids & photos" as UpdateStats
    usecase "Visualiser sa progression détaillée" as ViewProgress
    
    UpdateStats ..> Login : <<include>>
    ViewProgress ..> Login : <<include>>
  }

  package "Espace Client (Mobile App)" {
    usecase "Consulter son programme assigné" as ViewProg
    
    ViewProg ..> Login : <<include>>
  }

  package "Gestion Opérationnelle (Web Staff)" {
    usecase "Gérer les dossiers Clients" as ManageClients
    usecase "Concevoir des Programmes" as DesignProgs
    usecase "Calculer les Macros" as CalcMacros
    
    ManageClients ..> Login : <<include>>
    DesignProgs ..> Login : <<include>>
    DesignProgs ..> CalcMacros : <<include>>
  }

  package "Administration & Stratégie" {
    usecase "Gérer l'équipe" as ManageStaff
    usecase "Gérer les paiements" as ManageMoney
    
    ManageStaff ..> Login : <<include>>
    ManageMoney ..> Login : <<include>>
  }
}

' Connections
Visitor -- ViewPublic
Visitor -- Signup

' Client access split by platform
Client -- ViewProg : "(Via Mobile)"
Client -- UpdateStats : "(Via Web)"
Client -- ViewProgress : "(Via Web)"

' Staff & Admin
Staff -- ManageClients
Staff -- DesignProgs

Admin -- ManageStaff
Admin -- ManageMoney

@enduml