@startuml ImmoSyndic_MVP_Web_Clean
left to right direction
skinparam packageStyle rectangle
skinparam shadowing false

actor "Mobile" as Mobile
actor "Résident" as Resident
actor "Syndic" as Syndic
actor "Administrateur" as Admin

rectangle "Système ImmoSyndic - Sprint 2 Web" {

  ' Auth central
  usecase "S'authentifier" as Auth
' API
  usecase "Consommer API" as ProvideAPI

  ' Résident
  usecase "Signaler un problème" as ReportIssue
  usecase "Recevoir notifications" as GetNotifs
  usecase "Consulter archives" as ViewArchives


  ' Syndic
  usecase "gerer charges" as ManageCharges
  usecase "suivre interventions" as TrackInterventions
  usecase "gérer documents" as ManageDocuments
  usecase "envoyer annonces" as SendNews

  ' Admin
  usecase "consulter logs système" as ViewLogs
  usecase "Surveiller activités" as MonitorActivity


  ' includes → كلشي كيمشي ل Auth
  ReportIssue ..> Auth : <<include>>
  GetNotifs ..> Auth : <<include>>
  ViewArchives ..> Auth : <<include>>
  ManageCharges ..> Auth : <<include>>
  TrackInterventions ..> Auth : <<include>>
  ManageDocuments ..> Auth : <<include>>
  SendNews ..> Auth : <<include>>
  ViewLogs ..> Auth : <<include>>
  MonitorActivity ..> Auth : <<include>>
}

' Actors connections 
Mobile -- ProvideAPI

Resident -- ReportIssue
Resident -- GetNotifs
Resident -- ViewArchives

Syndic -- ManageCharges
Syndic -- TrackInterventions
Syndic -- ManageDocuments
Syndic -- SendNews

Admin -- ViewLogs
Admin -- MonitorActivity



@enduml