@startuml ImmoSyndic_Sprint2_Mobile
left to right direction
skinparam packageStyle rectangle
skinparam shadowing false

actor "Résident" as Resident
actor "Web" as Web <<System>>

rectangle "Application Mobile ImmoSyndic (Sprint 2)" {

  package "Session" {
    usecase "S'authentifier" as Auth
  }

  package "Services API (Sprint 2)" {
    usecase "Fournir API" as ProvideAPI
    usecase "API Payer une charge" as APIMobilePayCharge
    usecase "API Signaler un incident" as APIMobileReportIncident
    usecase "API Télécharger document PDF" as APIMobileDownloadPDF
    usecase "API Paramétrer profil" as APIMobileManageProfile

    ProvideAPI ..> APIMobilePayCharge : <<include>>
    ProvideAPI ..> APIMobileReportIncident : <<include>>
    ProvideAPI ..> APIMobileDownloadPDF : <<include>>
    ProvideAPI ..> APIMobileManageProfile : <<include>>

    APIMobilePayCharge ..> Auth : <<include>>
    APIMobileReportIncident ..> Auth : <<include>>
    APIMobileDownloadPDF ..> Auth : <<include>>
    APIMobileManageProfile ..> Auth : <<include>>
  }
}

' Users Connections
Resident -- APIMobilePayCharge
Resident -- APIMobileReportIncident
Resident -- APIMobileDownloadPDF
Resident -- APIMobileManageProfile

' Backend Connections (Data Source)
Web -- ProvideAPI

@enduml
