@startuml ImmoSyndic_MVP_Web_Clean
left to right direction
skinparam packageStyle rectangle
skinparam shadowing false

actor "Mobile" as Mobile
actor "Résident" as Resident
actor "Syndic" as Syndic
actor "Administrateur" as Admin

rectangle "Système ImmoSyndic - Sprint 1 Web" {

  ' Auth central
  usecase "S'authentifier" as Auth
' API
  usecase "Consommer API" as ProvideAPI

  ' Résident
  usecase "Consulter charges" as ViewCharges
  usecase "Consulter annonces" as ViewNews

  ' Syndic
  usecase "Gérer résidents" as ManageResidents
  usecase "Gérer immeubles" as ManageBuildings
  usecase "Suivre paiements" as TrackPayments

  ' Admin
  usecase "Gérer comptes résidents" as ManageUsers
  usecase "Gérer comptes syndic" as ManageSyndic
  usecase "Gérer droits" as ManageRoles



  ' includes → كلشي كيمشي ل Auth
  ViewCharges ..> Auth : <<include>>
  ViewNews ..> Auth : <<include>>
  ManageResidents ..> Auth : <<include>>
  ManageBuildings ..> Auth : <<include>>
  TrackPayments ..> Auth : <<include>>
  ManageUsers ..> Auth : <<include>>
  ManageSyndic ..> Auth : <<include>>
  ManageRoles ..> Auth : <<include>>
}

' Actors connections (مرتبين)
Mobile -- ProvideAPI
Resident -- ViewCharges
Resident -- ViewNews

Syndic -- ManageResidents
Syndic -- ManageBuildings
Syndic -- TrackPayments

Admin -- ManageUsers
Admin -- ManageSyndic
Admin -- ManageRoles



@enduml