@startuml
left to right direction
skinparam packageStyle rectangle
skinparam shadowing false

actor "Résident" as Resident
actor "Syndic" as Syndic
actor "Administrateur" as Admin

rectangle "Système ImmoSyndic (Solution Web & Mobile) - Sprint 1 (MVP)" {

  ' Authentification commune
  usecase "S'authentifier" as Auth
  usecase "Gérer profil" as Profile

  Resident -- Auth
  Syndic -- Auth
  Admin -- Auth
  
  Resident -- Profile
  Syndic -- Profile
  Admin -- Profile

  package "Espace Résident" {
    Resident -- (Créer compte)
    Resident -- (Consulter charges)
    Resident -- (Signaler problème)
    Resident -- (Recevoir notifications)
  }

  package "Espace Syndic" {
    Syndic -- (Gérer immeubles)
    Syndic -- (Suivre paiements)
    Syndic -- (Générer reçus)
    Syndic -- (Suivre interventions)
    Syndic -- (Consulter historique)
  }

  package "Espace Administrateur" {
    Admin -- (Gérer comptes)
    Admin -- (Superviser immeubles)
    Admin -- (Valider données)
    Admin -- (Gérer droits)
  }

}
@enduml