@startuml
left to right direction

actor Syndic
actor "Résident / Copropriétaire" as Resident
actor Administrateur

rectangle "Système de Gestion du Syndic" {

  ' -------- Syndic --------
  Syndic -- (Créer un compte Syndic)
  Syndic -- (Ajouter un paiement)
  Syndic -- (Valider un paiement)
  Syndic -- (Envoyer un reçu)
  Syndic -- (Gérer les informations de l’immeuble)
  Syndic -- (Consulter l’état des paiements)

  ' -------- Résident --------
  Resident -- (Créer un compte Résident)
  Resident -- (Consulter ses paiements)
  Resident -- (Payer ses charges)
  Resident -- (Signaler un problème)

  ' -------- Administrateur --------
  Administrateur -- (Valider le remplacement d’un Syndic)
  Administrateur -- (Superviser les paiements)
  Administrateur -- (Mettre à jour la liste des Syndics)

  ' -------- Relations Include --------
  (Valider un paiement) .> (Envoyer un reçu) : <<include>>
  (Payer ses charges) .> (Envoyer un reçu) : <<include>>

}
@enduml